version: '3.8'
services:
  client-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-client-service
    restart: always
    ports:
      - 8083:8083
    networks:
      bank_network:
        aliases:
          - app_subnet
        #ipv4_address: 172.20.0.4
networks:
  bank_network:
    name: app_subnet
    external: true